[package]
name = "func-sel-miner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
hex = "0.4.3"
rayon = "1.5.1"
num_cpus = "1.13.0"